controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /login_check
    methods: POST

api_refresh_token:
    path: /token/refresh
    methods: POST
